services:
  web:
    build: .
    links:
      - db
    ports:
      - "8080:8080"
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: rebuild
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
  db:
    container_name: mydb-tmp
    image: mysql:8.0
    ports:
        - "32000:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    name: "mysql-db-volume-tmp"