services:
  web:
    build: .
    depends_on:
      - ldap
      - db
    ports:
      - "8080:8080"
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: rebuild
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
  db:
    container_name: mydb-tmp
    image: mysql:8.0
    ports:
        - "32000:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  ldap:
      image: bitnami/openldap:latest
      environment:
        - LDAP_ADMIN_USERNAME=admin
        - LDAP_ADMIN_PASSWORD=adminpassword
        - LDAP_USER_DN=ou=users,dc=example,dc=com
        - LDAP_GROUP_DN=ou=groups,dc=example,dc=com
      ports:
        - "389:389"
      volumes:
        - ./ldap/initialize_ldap.sh:/docker-entrypoint-initdb.d/initialize_ldap.sh

volumes:
  db:
    name: "mysql-db-volume-tmp"